### PR TITLE
Add Google Maps API v3

### PR DESCRIPTION
**Pull request by ghost**
-- Add API JSs
-- Add API calls to set markers, add routing, get directions, geo names, etc
- NOTEs:
  -- The Google API key should be replaced with something else
  -- Maybe leave it under review for now or remove user-visible parts before merging
- TODOs
  -- Save routing to Parse DB
  -- Change from/to when dragging route markers
  -- Re-show routing when editing
  -- Fix collapsing/expanding of the map control inside bootstrap modal

### CODE REVIEW

**Comment by grigy** [comment]
@vhpoet @isajanyan do we want to merge this now?

**Comment by ghost** [comment]
Not really.
Just a starting point for you or me if we decide to integrate maps api

**Comment by siavash1986** [comment]
Hi there,
I'm already working on Google maps API, I'm finalizing my code in a day or two and share it with you. here is how it look like: www.iransoil.com/freecar/

**Comment by ghost** [comment]
Coolness!!!

**Pull request closed without merging**
